# Generated by Django 4.1.7 on 2023-02-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccines", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccine",
            name="visit",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
